# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Wed, 17 Sep 2014 17:07:49 +0000
*               @ALL          1
*               @user         8
