<?php
/*
 * Local plugin enable/disable settings
 *
 * Auto-generated by install script
 * Date: Wed, 17 Sep 2014 17:07:49 +0000
 */

$plugins['authad']    = 0;
$plugins['authldap']  = 0;
$plugins['authmysql'] = 0;
$plugins['authpgsql'] = 0;
